apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: windows11-installer-run-
spec:
  params:
    - name: winImageDownloadURL
      value: INSERT_WINDOWS_ISO_URL
  pipelineRef:
    resolver: hub
    params:
    - name: catalog
      value: kubevirt-tekton-pipelines
    - name: type
      value: artifact
    - name: kind
      value: task
    - name: name
      value: windows-efi-installer
    - name: version
      value: v0.18.0
  serviceAccountName: pipeline
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: windows2k22-installer-run-
spec:
  params:
    - name: winImageDownloadURL
      value: INSERT_WINDOWS_ISO_URL
    - name: preferenceName
      value: "windows.2k22"
    - name: autounattendConfigMapName
      value: windows2k22-autounattend
    - name: baseDvName
      value: win2k22
    - name: isoDVName
      value: win2k22
  pipelineRef:
    resolver: hub
    params:
    - name: catalog
      value: kubevirt-tekton-pipelines
    - name: type
      value: artifact
    - name: kind
      value: task
    - name: name
      value: windows-efi-installer
    - name: version
      value: v0.18.0
  timeout: 1h0m0s
  serviceAccountName: pipeline      
